# Generated by Django 4.2.5 on 2023-09-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
